apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crabbot.fullname" . }}

  labels:
    app.kubernetes.io/name: {{ include "crabbot.name" . }}
    helm.sh/chart: {{ include "crabbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.secrets.discordToken }}
  DISCORD_TOKEN: {{ .Values.secrets.discordToken | b64enc | quote }}
  {{ end }}

  {{ if .Values.secrets.autoCodeToken }}
  AUTOCODE_TOKEN: {{ .Values.secrets.autoCodeToken | b64enc | quote }}
  {{ end }}